[package]
name = "geth"
version = "1.17.0"
build = "1"

[docker]
repository = "chainargos/geth"
platforms = ["amd64", "arm64"]

[vars]
git_commit = "0cf3d3ba"
legacy_version = "1.13.15"
legacy_git_commit = "c5ba367e"
