[package]
name = "geth"
version = "1.16.8"
build = "1"

[docker]
repository = "donbeave/geth"
platforms = ["amd64", "arm64"]

[vars]
git_commit = "abeb78c6"
legacy_version = "1.13.15"
legacy_git_commit = "c5ba367e"
